//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDAXayDung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TienDoDA
    {
        [Display(Name = "Mã tiến độ")]
        public int MaTD { get; set; }
        [Display(Name = "Mã dự án")]
        public string MaDA { get; set; }
        [Display(Name = "Công việc")]
        public string CongViec { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        [Display(Name = "Ngày kết thúc")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        [Display(Name = "Dự án")]
        public virtual DuAn DuAn { get; set; }
    }
}
