//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDAXayDung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VatTuTrongDuAn
    {
        [Display(Name = "Mã Vật Tư")]
        public int MaVT { get; set; }

        [Display(Name = "Mã Dự Án")]
        public string MaDA { get; set; }

        [Display(Name = "Số Lượng")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Dự Án")]
        public virtual DuAn DuAn { get; set; }

        [Display(Name = "Vật Tư")]
        public virtual VatTu VatTu { get; set; }
    }
}
