//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDAXayDung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class VatTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VatTu()
        {
            this.VatTuTrongDuAns = new HashSet<VatTuTrongDuAn>();
        }
        [Display(Name = "Mã vật tư")]
        public int MaVT { get; set; }

        [Display(Name = "Tên vật tư")]
        public string TenVT { get; set; }

        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Đơn vị tính")]
        public string ĐonViTinh { get; set; }

        [Display(Name = "Nhà cung cấp")]
        public Nullable<int> MaNCC { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VatTuTrongDuAn> VatTuTrongDuAns { get; set; }
    }
}
